In [53]:
#Add the repo root (one level up from this notebook) to sys.path
import sys, os
sys.path.insert(0, os.path.abspath("../"))
from experiments import *
Y_TRAIN, Y_TEST, train_df, test_df=load_data_and_split(.8)
data = {
    'Y_TRAIN': Y_TRAIN,
    'Y_TEST': Y_TEST,
    'train_df': train_df,
    'test_df': test_df
}

Load or download dataset...
Warning: Looks like you're using an outdated `kagglehub` version, please consider updating (latest version: 0.3.12)
Loading fake.csv ...
Loading true.csv ...
Done

In [54]:
# options = {
#     'z_score_options': [True, False],
#     'sparse_options': [True, False],
#     'columns_list': [['title'], ['text'], ['title', 'text']],
#     'models': ['LogisticRegression', 'LinearSVM', 'MLP'],
#     'C_list': [1, 10, 100],
#     'hidden_layer_widths_list': [[10], [100, 10]],
#     'vectorizations': ['tf-idf', 'bag-of-words'],
#     'tokenizers': {
#         'None': None,
#         'basic': basic_word_tokenizer,
#         'lemmatization': lemmatization_tokenizer,
#         'stemming': stemming_tokenizer
#     },
#     'stop_words_options': [None, 'english'],
#     'ngram_ranges': [(1, 1), (2, 2), (1, 5)],
#     'max_features_list': [1000, None],
#     'activations': ['ReLU', 'Sigmoid', 'Softmax', 'Linear'],
#     'lrs': [1e-6, 1e-5, 1e-4, 1e-3, 1e-2, 1e-1, 1],
#     'bss': [100, len(train_df)],
#     'epochs_list': [100],
#     'compute_metrics': False,
#     'metrics_dict': None,
#     'filename': None
# }

# column_order=['sparse','z-score','columns','model', '# epochs','learning rate','batch size','C','widths','activation','vectorization','tokenizer','stop_words',
#     'ngram range','# features','train accuracy [%]','test accuracy [%]','vectorization time [s]','training time [s]'
#     ]

# result_df, histories=run_experiments(column_order=column_order, **options, **data)

In [55]:
options = {
    'z_score_options': [True],
    'sparse_options': [True],
    'models': ['LogisticRegression'],
    'columns_list': [['title']],
    'vectorizations': ['tf-idf'],
    'tokenizers': {
        'None': None,
    },
    'stop_words_options': [None],
    'ngram_ranges': [(1, 1)],
    'max_features_list': [None],
    'lrs':  [alpha* 10**k for k in range(-5,3) for alpha in [0.5,1]],
    'bss': [len(train_df)],
    'epochs_list': [100],
    'compute_metrics': False,
    'metrics_dict': None,
    'filename': "LogisticRegression_full_batch.csv"
}
column_order=['model','learning rate','batch size','train accuracy [%]','test accuracy [%]','training time [s]'
    ]

result_df, histories=run_experiments(column_order=column_order, **options, **data)

In [56]:
result_df[(result_df['train accuracy [%]']>=99) & (result_df['test accuracy [%]']>=95)][column_order]

,model,learning rate,batch size,train accuracy [%],test accuracy [%],training time [s]
9,LogisticRegression,0.1,35918,99.0952,96.1581,0.45
10,LogisticRegression,0.5,35918,99.7661,95.7350,0.44
11,LogisticRegression,1.0,35918,99.9165,95.5791,0.44
12,LogisticRegression,5.0,35918,100.0000,95.6125,0.44
13,LogisticRegression,10.0,35918,100.0000,95.7127,0.46
14,LogisticRegression,50.0,35918,100.0000,95.9354,0.50
15,LogisticRegression,100.0,35918,100.0000,95.9577,0.44

In [57]:
options = {
    'z_score_options': [True],
    'sparse_options': [True],
    'models': ['LinearSVM'],
    'columns_list': [['title']],
    'vectorizations': ['tf-idf'],
    'tokenizers': {
        'None': None,
    },
    'stop_words_options': [None],
    'ngram_ranges': [(1, 1)],
    'max_features_list': [None],
    'lrs': [alpha* 10**k for k in range(-5,1) for alpha in [0.5,1]],
    'bss': [len(train_df)],
    'epochs_list': [100],
    'compute_metrics': False,
    'metrics_dict': None,
    'filename': "LinearSVM_full_batch.csv",
    'C_list': [0.1,1,10,100],
}
column_order=['model', '# epochs','learning rate','C','# features','train accuracy [%]','test accuracy [%]','vectorization time [s]','training time [s]'
    ]

result_df, histories=run_experiments(column_order=column_order, **options, **data)

In [58]:
result_df[(result_df['train accuracy [%]']>=99) & (result_df['test accuracy [%]']>=95)][column_order]

,model,# epochs,learning rate,C,# features,train accuracy [%],test accuracy [%],vectorization time [s],training time [s]
15,LinearSVM,100,0.0001,100.0,19572,99.4738,95.6570,0.58,0.72
22,LinearSVM,100,0.0010,10.0,19572,99.3708,95.6236,0.58,0.75

In [59]:
options = {
    'z_score_options': [True],
    'sparse_options': [True],
    'models': ['LogisticRegression'],
    'columns_list': [['title']],
    'vectorizations': ['tf-idf'],
    'tokenizers': {
        'None': None,
    },
    'stop_words_options': [None],
    'ngram_ranges': [(1, 1)],
    'max_features_list': [None],
    'lrs':  [alpha* 10**k for k in range(-5,3) for alpha in [0.5,1]],
    'bss': [100],
    'epochs_list': [100],
    'compute_metrics': False,
    'metrics_dict': None,
    'filename': "LogisticRegression_mini_batch.csv"
}
column_order=['model','learning rate','batch size','train accuracy [%]','test accuracy [%]','training time [s]'
    ]

result_df, histories=run_experiments(column_order=column_order, **options, **data)

In [60]:
result_df[(result_df['train accuracy [%]']>=99) & (result_df['test accuracy [%]']>=95)][column_order]

,model,learning rate,batch size,train accuracy [%],test accuracy [%],training time [s]
4,LogisticRegression,0.0005,100,99.4571,96.0690,8.94
5,LogisticRegression,0.0010,100,99.6770,95.9020,8.91
6,LogisticRegression,0.0050,100,99.9694,95.4454,8.97
7,LogisticRegression,0.0100,100,100.0000,95.1670,8.89

In [61]:
options = {
    'z_score_options': [True],
    'sparse_options': [True],
    'models': ['LinearSVM'],
    'columns_list': [['title']],
    'vectorizations': ['tf-idf'],
    'tokenizers': {
        'None': None,
    },
    'stop_words_options': [None],
    'ngram_ranges': [(1, 1)],
    'max_features_list': [None],
    'lrs': [alpha* 10**k for k in range(-5,1) for alpha in [0.5,1]],
    'bss': [100],
    'epochs_list': [100],
    'compute_metrics': False,
    'metrics_dict': None,
    'filename': "LinearSVM_mini_batch.csv",
    'C_list': [0.1,1,10,100],
}
column_order=['model', '# epochs','learning rate','C','# features','train accuracy [%]','test accuracy [%]','vectorization time [s]','training time [s]'
    ]

result_df, histories=run_experiments(column_order=column_order, **options, **data)

In [62]:
result_df[(result_df['train accuracy [%]']>=99) & (result_df['test accuracy [%]']>=95)][column_order]

,model,# epochs,learning rate,C,# features,train accuracy [%],test accuracy [%],vectorization time [s],training time [s]
2,LinearSVM,100,0.000005,10.0,19572,99.8023,95.2339,0.58,25.91

In [63]:
options = {
    'z_score_options': [False],
    'sparse_options': [False],
    'columns_list': [['title']],
    'models': ['MLP'],
    'hidden_layer_widths_list': [[16],[128], [256]],
    'vectorizations': ['tf-idf'],
    'tokenizers': {
        'None': None
    },
    'stop_words_options': [None],
    'ngram_ranges': [(1, 1)],
    'max_features_list': [1000, 5000, 10000],
    'activations': ['ReLU'],
    'lrs': [10],
    'bss': [128],
    'epochs_list': [25],
    'compute_metrics': False,
    'metrics_dict': None,
    'filename': "MLP.csv"
}

column_order=['model','widths','train accuracy [%]','test accuracy [%]','training time [s]'
    ]


result_df, histories=run_experiments(column_order=column_order, **options, **data)

In [64]:
options = {
    'z_score_options': [True],
    'sparse_options': [False],
    'columns_list': [['title']],
    'models': ['MLP'],
    'hidden_layer_widths_list': [[16],[128], [256]],
    'vectorizations': ['tf-idf'],
    'tokenizers': {
        'None': None
    },
    'stop_words_options': [None],
    'ngram_ranges': [(1, 1)],
    'max_features_list': [1000, 5000, 10000],
    'activations': ['ReLU'],
    'lrs': [10],
    'bss': [128],
    'epochs_list': [25],
    'compute_metrics': False,
    'metrics_dict': None,
    'filename': "MLP.csv"
}

column_order=['model','widths','train accuracy [%]','test accuracy [%]','training time [s]'
    ]


result_df, histories=run_experiments(column_order=column_order, **options, **data)